### model
model_name_or_path: meta-llama/Llama-2-7b-hf

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
additional_target: embed_tokens
lora_rank: 16

### dataset
dataset: gsm
template: empty
cutoff_len: 256
packing: false
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama2-gsm/
logging_steps: 10
save_steps: 500
plot_loss: false
save_total_limit: 2
overwrite_output_dir: true

### train
per_device_train_batch_size: 128
gradient_accumulation_steps: 1
learning_rate: 3.0e-4
num_train_epochs: 40.0
lr_scheduler_type: cosine
warmup_steps: 2000
bf16: true
ddp_timeout: 180000000

### eval
val_size: 256
per_device_eval_batch_size: 128
eval_strategy: steps
eval_steps: 200
