### model
model_name_or_path: gpt2-medium
checkpoint_dir: output/gpt2-ddm/checkpoint-160000/
print_param_status: true

### method
stage: ddm-sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: gsm
template: empty
cutoff_len: 256
streaming: false
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/gpt2-ddm-gsm-v2/
logging_steps: 10
save_steps: 1000
save_total_limit: 2
plot_loss: false
overwrite_output_dir: true

### train
per_device_train_batch_size: 128
gradient_accumulation_steps: 1
learning_rate: 3.0e-4
num_train_epochs: 200.0
lr_scheduler_type: cosine
warmup_steps: 2000
bf16: true
ddp_timeout: 180000000
anneal_steps: 1
shift: true
remove_unused_columns: false

### eval
val_size: 64
per_device_eval_batch_size: 64
eval_strategy: steps
eval_steps: 1000
