### model
model_name_or_path: gpt2

### method
stage: ddm
shift: true
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: fineweb
template: empty
packing: true
cutoff_len: 1024
streaming: false
tokenized_path: output/gpt2-fineweb-tokenized/
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/gpt2-ddm-small-v6/
logging_steps: 10
save_steps: 10000
save_total_limit: 3
plot_loss: false
overwrite_output_dir: true

### train
per_device_train_batch_size: 160
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
max_steps: 10000
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 100
bf16: true
ddp_timeout: 180000000
max_grad_norm: 1.0

### eval
val_size: 160
per_device_eval_batch_size: 160
eval_strategy: steps
eval_steps: 1000
