### model
model_name_or_path: diffusionfamily/diffullama
print_param_status: true

### method
stage: ddm-sft
do_train: true
finetuning_type: lora
lora_target: all
additional_target: embed_tokens
lora_rank: 16

### dataset
dataset: my_dataset
template: empty
cutoff_len: 256
streaming: false
overwrite_cache: true

### output
output_dir: output/my-diffullama-finetuned/
logging_steps: 10
save_steps: 2000

### train
per_device_train_batch_size: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
bf16: true
anneal_steps: 1
shift: true