### model
model_name_or_path: Dream-org/Dream-v0-Instruct-7B
hf_hub_token: 
print_param_status: true

### method
stage: ddm-sft
# stage: ddm
do_train: true
finetuning_type: full

### dataset
dataset: my_dataset
template: empty
cutoff_len: 128
streaming: false
overwrite_cache: true

### output
output_dir: output/my-diffullama-finetuned-v3/
logging_steps: 10
save_total_limit: 1
save_steps: 200
# push_to_hub: true
# hub_model_id: myduy/test-diffusionlm-v2

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
weight_decay: 0.01
warmup_ratio: 0.1
lr_scheduler_type: cosine
num_train_epochs: 3.0
bf16: true
anneal_steps: 1
shift: true
optim: adamw_8bit

### wandb logging
report_to: wandb
run_name: finetune-dream-7b-v1

### optional: push to huggingface hub after training
export_hub_model_id: "myduy/test-diffusionlm-v3"
